import { Code2, ExternalLink } from "lucide-react";

const githubBase = "https://github.com/2022123167a";

const projects = [
  {
    name: "No-Code Platform Runtime System",
    description:
      "A runtime system built with Flet that reads JSON schemas generated by a drag-and-drop frontend designer and dynamically renders UI pages. The system supports components, layouts, tables, buttons, events, HTTP actions, state management, and backend integration.",
    tech: ["Flet", "Python", "REST APIs", "JSON", "Runtime Rendering"],
    github: `${githubBase}/no-code-platform-runtime`, // Replace with the real repository link.
    live: "https://CHANGE_THIS_TO_LIVE_DEMO_URL.com", // Replace with the real live demo link.
  },
  {
    name: "Chatify - Web Messaging Application",
    description:
      "A web-based messaging application built using Node.js, HTML, CSS, JavaScript, and MongoDB Cloud. It supports user and chat data storage and demonstrates full-stack web development concepts.",
    tech: ["Node.js", "JavaScript", "HTML", "CSS", "MongoDB Cloud"],
    github: `${githubBase}/chatify`, // Replace with the real repository link.
    live: "https://CHANGE_THIS_TO_LIVE_DEMO_URL.com", // Replace with the real live demo link.
  },
  {
    name: "Raspberry Pi Face Recognition Door Lock",
    description:
      "A smart door lock system using Raspberry Pi and OpenCV. It implements face recognition for user authentication and integrates hardware with software components.",
    tech: ["Raspberry Pi", "Python", "OpenCV", "Embedded Systems"],
    github: `${githubBase}/raspberry-pi-face-lock`, // Replace with the real repository link.
    live: "https://CHANGE_THIS_TO_LIVE_DEMO_URL.com", // Replace with the real live demo link.
  },
];

function Projects() {
  return (
    <section id="projects" className="section-container">
      <p className="section-kicker">Projects</p>
      <h2 className="section-heading">Selected Work</h2>
      <div className="mt-10 grid gap-5 lg:grid-cols-3">
        {projects.map((project) => (
          <article key={project.name} className="glass-card hover-lift flex flex-col p-6">
            <h3 className="text-xl font-bold text-white">{project.name}</h3>
            <p className="mt-4 flex-1 text-sm leading-7 text-slate-300">{project.description}</p>
            <div className="mt-6 flex flex-wrap gap-2">
              {project.tech.map((item) => (
                <span key={item} className="rounded-full bg-white/[0.07] px-3 py-1 text-xs text-slate-200">
                  {item}
                </span>
              ))}
            </div>
            <div className="mt-7 flex flex-col gap-3 sm:flex-row lg:flex-col xl:flex-row">
              <a href={project.github} target="_blank" rel="noreferrer" className="secondary-button">
                <Code2 size={17} /> GitHub
              </a>
              <a href={project.live} target="_blank" rel="noreferrer" className="primary-button">
                <ExternalLink size={17} /> Live Demo
              </a>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}

export default Projects;
