import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      nav: {
        toggle: "Toggle navigation menu",
        links: {
          home: "Home",
          about: "About",
          skills: "Skills",
          experience: "Experience",
          projects: "Projects",
          education: "Education",
          contact: "Contact",
        },
      },
      language: {
        label: "Language",
        en: "EN",
        ar: "AR",
        tr: "TR",
      },
      hero: {
        location: "Based in Sivas, Turkey",
        greeting: "Hi, I'm Ahmed Sherif",
        title: "Junior Full-Stack Developer",
        intro:
          "Computer Engineering graduate with hands-on experience in full-stack development, frontend systems, backend integration, and runtime rendering architectures.",
        viewProjects: "View Projects",
        contactMe: "Contact Me",
        downloadCv: "Download CV",
        linkedin: "Ahmed Sherif on LinkedIn",
        github: "Ahmed Sherif on GitHub",
      },
      about: {
        kicker: "About",
        heading: "A developer who connects frontend, backend, and systems thinking.",
        body:
          "I am a Computer Engineering graduate with experience in full-stack development, frontend systems, backend integration, and runtime rendering architectures. I have worked on real-world software projects involving Angular, React, Node.js, Flet, REST APIs, MongoDB, and JSON-based UI systems. I also have experience in networking through Cisco CCNA/CCNP and embedded systems through Raspberry Pi and OpenCV.",
        highlights: [
          "Full-stack software projects",
          "CCNA / CCNP networking foundation",
          "Runtime and JSON-based UI systems",
        ],
      },
      skills: {
        kicker: "Skills",
        heading: "Technical Toolkit",
        groups: [
          { title: "Programming Languages", skills: ["Java", "C#", "JavaScript", "TypeScript", "Python"] },
          { title: "Frontend", skills: ["Angular", "React", "HTML", "CSS", "Tailwind CSS", "Responsive Design"] },
          { title: "Backend", skills: ["Node.js", "REST APIs"] },
          { title: "Database", skills: ["MongoDB", "SQL"] },
          { title: "Tools & Technologies", skills: ["Git", "GitHub", "Flet", "Raspberry Pi", "OpenCV"] },
          {
            title: "Concepts",
            skills: [
              "API Integration",
              "Authentication",
              "Runtime Rendering",
              "UI Rendering",
              "State Management",
              "JSON-based UI Systems",
            ],
          },
        ],
      },
      experience: {
        kicker: "Experience",
        heading: "Professional Experience",
        items: [
          {
            title: "No-Code Platform Runtime Developer",
            company: "IDEA Teknoloji",
            date: "2026 - Present",
            bullets: [
              "Developed a runtime rendering system using Flet for a no-code platform.",
              "Rendered dynamic UI components from JSON schemas generated by the frontend designer.",
              "Implemented event handling, API requests, and state management logic.",
              "Collaborated with frontend and backend teams in a real development environment.",
              "Worked on rendering tables, layouts, buttons, icons, and dynamic actions.",
            ],
          },
          {
            title: "Web Development Intern",
            company: "Beşir Camaleddin Company",
            date: "2025",
            bullets: [
              "Assisted in frontend and backend web application development.",
              "Participated in team-based development workflows.",
              "Worked with APIs and UI integration tasks.",
            ],
          },
        ],
      },
      projects: {
        kicker: "Projects",
        heading: "Selected Work",
        github: "GitHub",
        liveDemo: "Live Demo",
        items: [
          {
            name: "No-Code Platform Runtime System",
            description:
              "A runtime system built with Flet that reads JSON schemas generated by a drag-and-drop frontend designer and dynamically renders UI pages. The system supports components, layouts, tables, buttons, events, HTTP actions, state management, and backend integration.",
            tech: ["Flet", "Python", "REST APIs", "JSON", "Runtime Rendering"],
          },
          {
            name: "Chatify - Web Messaging Application",
            description:
              "A web-based messaging application built using Node.js, HTML, CSS, JavaScript, and MongoDB Cloud. It supports user and chat data storage and demonstrates full-stack web development concepts.",
            tech: ["Node.js", "JavaScript", "HTML", "CSS", "MongoDB Cloud"],
          },
          {
            name: "Raspberry Pi Face Recognition Door Lock",
            description:
              "A smart door lock system using Raspberry Pi and OpenCV. It implements face recognition for user authentication and integrates hardware with software components.",
            tech: ["Raspberry Pi", "Python", "OpenCV", "Embedded Systems"],
          },
        ],
      },
      education: {
        kicker: "Education",
        heading: "Education, Certifications & Languages",
        university: "Sivas Cumhuriyet University",
        degree: "B.Sc. in Computer Engineering",
        educationDate: "2022 - 2026",
        graduating: "Graduating in 2026",
        certification: "Cisco CCNA / CCNP",
        academy: "Cisco Networking Academy",
        certificationDate: "2021 - 2022",
        languagesTitle: "Languages",
        languages: ["Arabic - Native", "Turkish - Advanced (C1)", "English - Intermediate (B1)"],
      },
      contact: {
        kicker: "Contact",
        heading: "Let's Build Something",
        email: "Email",
        phone: "Phone",
        location: "Location",
        locationValue: "Based in Sivas, Turkey",
        nameLabel: "Name",
        namePlaceholder: "Your name",
        emailLabel: "Email",
        emailPlaceholder: "your@email.com",
        messageLabel: "Message",
        messagePlaceholder: "Tell me about your project or opportunity",
        send: "Send Message",
        sending: "Sending...",
        success: "Thank you. Your message has been sent successfully.",
        error: "Sorry, the message could not be sent. Please try again or email me directly.",
      },
      footer: {
        rights: "© 2026 Ahmed Sherif. All rights reserved.",
        tagline: "Junior Full-Stack Developer · Egyptian Citizen",
      },
    },
  },
  ar: {
    translation: {
      nav: {
        toggle: "تبديل قائمة التنقل",
        links: {
          home: "الرئيسية",
          about: "نبذة",
          skills: "المهارات",
          experience: "الخبرة",
          projects: "المشاريع",
          education: "التعليم",
          contact: "تواصل",
        },
      },
      language: {
        label: "اللغة",
        en: "EN",
        ar: "عربي",
        tr: "TR",
      },
      hero: {
        location: "مقيم في سيواس، تركيا",
        greeting: "مرحبًا، أنا أحمد شريف",
        title: "مطور Full-Stack مبتدئ",
        intro:
          "خريج هندسة حاسوب لدي خبرة عملية في تطوير الويب الكامل، أنظمة الواجهة الأمامية، تكامل الواجهة الخلفية، وبناء أنظمة العرض وقت التشغيل.",
        viewProjects: "عرض المشاريع",
        contactMe: "تواصل معي",
        downloadCv: "تحميل السيرة الذاتية",
        linkedin: "أحمد شريف على LinkedIn",
        github: "أحمد شريف على GitHub",
      },
      about: {
        kicker: "نبذة",
        heading: "مطور يجمع بين الواجهة الأمامية والخلفية والتفكير البرمجي المنظم.",
        body:
          "أنا خريج هندسة حاسوب لدي خبرة في تطوير الويب الكامل، أنظمة الواجهة الأمامية، تكامل الواجهة الخلفية، وبناء أنظمة العرض وقت التشغيل. عملت على مشاريع برمجية واقعية باستخدام Angular و React و Node.js و Flet و REST APIs و MongoDB وأنظمة واجهات مبنية على JSON. لدي أيضًا خبرة في الشبكات من خلال Cisco CCNA/CCNP وفي الأنظمة المدمجة من خلال Raspberry Pi و OpenCV.",
        highlights: [
          "مشاريع برمجية Full-Stack",
          "أساس قوي في الشبكات CCNA / CCNP",
          "أنظمة عرض وقت التشغيل وواجهات JSON",
        ],
      },
      skills: {
        kicker: "المهارات",
        heading: "الأدوات التقنية",
        groups: [
          { title: "لغات البرمجة", skills: ["Java", "C#", "JavaScript", "TypeScript", "Python"] },
          { title: "الواجهة الأمامية", skills: ["Angular", "React", "HTML", "CSS", "Tailwind CSS", "تصميم متجاوب"] },
          { title: "الواجهة الخلفية", skills: ["Node.js", "REST APIs"] },
          { title: "قواعد البيانات", skills: ["MongoDB", "SQL"] },
          { title: "الأدوات والتقنيات", skills: ["Git", "GitHub", "Flet", "Raspberry Pi", "OpenCV"] },
          {
            title: "المفاهيم",
            skills: [
              "تكامل API",
              "المصادقة",
              "العرض وقت التشغيل",
              "عرض الواجهة",
              "إدارة الحالة",
              "أنظمة واجهات مبنية على JSON",
            ],
          },
        ],
      },
      experience: {
        kicker: "الخبرة",
        heading: "الخبرة العملية",
        items: [
          {
            title: "مطور نظام تشغيل لمنصة No-Code",
            company: "IDEA Teknoloji",
            date: "2026 - حتى الآن",
            bullets: [
              "طورت نظام عرض وقت التشغيل باستخدام Flet لمنصة No-Code.",
              "عرضت مكونات واجهة ديناميكية من JSON schemas مولدة من مصمم الواجهة.",
              "نفذت منطق الأحداث وطلبات API وإدارة الحالة.",
              "تعاونت مع فرق الواجهة الأمامية والخلفية في بيئة تطوير واقعية.",
              "عملت على عرض الجداول والتخطيطات والأزرار والأيقونات والإجراءات الديناميكية.",
            ],
          },
          {
            title: "متدرب تطوير ويب",
            company: "شركة بشير جمال الدين",
            date: "2025",
            bullets: [
              "ساعدت في تطوير تطبيقات ويب للواجهة الأمامية والخلفية.",
              "شاركت في سير عمل تطوير جماعي.",
              "عملت على مهام تكامل API والواجهة.",
            ],
          },
        ],
      },
      projects: {
        kicker: "المشاريع",
        heading: "أعمال مختارة",
        github: "GitHub",
        liveDemo: "عرض مباشر",
        items: [
          {
            name: "نظام تشغيل لمنصة No-Code",
            description:
              "نظام Runtime مبني باستخدام Flet يقرأ JSON schemas مولدة من مصمم واجهات بالسحب والإفلات ويعرض صفحات واجهة ديناميكية. يدعم المكونات والتخطيطات والجداول والأزرار والأحداث وطلبات HTTP وإدارة الحالة والتكامل مع الخلفية.",
            tech: ["Flet", "Python", "REST APIs", "JSON", "Runtime Rendering"],
          },
          {
            name: "Chatify - تطبيق مراسلة ويب",
            description:
              "تطبيق مراسلة على الويب مبني باستخدام Node.js و HTML و CSS و JavaScript و MongoDB Cloud. يدعم تخزين بيانات المستخدمين والمحادثات ويوضح مفاهيم تطوير الويب الكامل.",
            tech: ["Node.js", "JavaScript", "HTML", "CSS", "MongoDB Cloud"],
          },
          {
            name: "قفل باب بالتعرف على الوجه باستخدام Raspberry Pi",
            description:
              "نظام قفل ذكي باستخدام Raspberry Pi و OpenCV. يطبق التعرف على الوجه للمصادقة ويربط بين مكونات الهاردوير والبرمجيات.",
            tech: ["Raspberry Pi", "Python", "OpenCV", "Embedded Systems"],
          },
        ],
      },
      education: {
        kicker: "التعليم",
        heading: "التعليم والشهادات واللغات",
        university: "جامعة سيواس جمهوريت",
        degree: "بكالوريوس هندسة الحاسوب",
        educationDate: "2022 - 2026",
        graduating: "التخرج في 2026",
        certification: "Cisco CCNA / CCNP",
        academy: "أكاديمية Cisco Networking Academy",
        certificationDate: "2021 - 2022",
        languagesTitle: "اللغات",
        languages: ["العربية - اللغة الأم", "التركية - متقدم (C1)", "الإنجليزية - متوسط (B1)"],
      },
      contact: {
        kicker: "تواصل",
        heading: "لنبنِ شيئًا معًا",
        email: "البريد الإلكتروني",
        phone: "الهاتف",
        location: "الموقع",
        locationValue: "مقيم في سيواس، تركيا",
        nameLabel: "الاسم",
        namePlaceholder: "اسمك",
        emailLabel: "البريد الإلكتروني",
        emailPlaceholder: "your@email.com",
        messageLabel: "الرسالة",
        messagePlaceholder: "اكتب رسالتك أو تفاصيل الفرصة",
        send: "إرسال الرسالة",
        sending: "جارٍ الإرسال...",
        success: "شكرًا لك. تم إرسال رسالتك بنجاح.",
        error: "عذرًا، تعذر إرسال الرسالة. حاول مرة أخرى أو راسلني مباشرة.",
      },
      footer: {
        rights: "© 2026 أحمد شريف. جميع الحقوق محفوظة.",
        tagline: "مطور Full-Stack مبتدئ · مواطن مصري",
      },
    },
  },
  tr: {
    translation: {
      nav: {
        toggle: "Menüyü aç veya kapat",
        links: {
          home: "Ana Sayfa",
          about: "Hakkımda",
          skills: "Yetenekler",
          experience: "Deneyim",
          projects: "Projeler",
          education: "Eğitim",
          contact: "İletişim",
        },
      },
      language: {
        label: "Dil",
        en: "EN",
        ar: "AR",
        tr: "TR",
      },
      hero: {
        location: "Sivas, Türkiye merkezli",
        greeting: "Merhaba, ben Ahmed Sherif",
        title: "Junior Full-Stack Developer",
        intro:
          "Full-stack geliştirme, frontend sistemleri, backend entegrasyonu ve runtime rendering mimarileri alanlarında pratik deneyime sahip Bilgisayar Mühendisliği mezunu.",
        viewProjects: "Projeleri Gör",
        contactMe: "İletişime Geç",
        downloadCv: "CV İndir",
        linkedin: "Ahmed Sherif LinkedIn profili",
        github: "Ahmed Sherif GitHub profili",
      },
      about: {
        kicker: "Hakkımda",
        heading: "Frontend, backend ve sistem düşüncesini birleştiren bir geliştirici.",
        body:
          "Bilgisayar Mühendisliği mezunuyum ve full-stack geliştirme, frontend sistemleri, backend entegrasyonu ve runtime rendering mimarileri alanlarında deneyime sahibim. Angular, React, Node.js, Flet, REST API'ler, MongoDB ve JSON tabanlı UI sistemleri içeren gerçek yazılım projelerinde çalıştım. Ayrıca Cisco CCNA/CCNP ile ağ teknolojileri, Raspberry Pi ve OpenCV ile gömülü sistemler konusunda deneyimim var.",
        highlights: [
          "Full-stack yazılım projeleri",
          "CCNA / CCNP ağ temeli",
          "Runtime ve JSON tabanlı UI sistemleri",
        ],
      },
      skills: {
        kicker: "Yetenekler",
        heading: "Teknik Araç Seti",
        groups: [
          { title: "Programlama Dilleri", skills: ["Java", "C#", "JavaScript", "TypeScript", "Python"] },
          { title: "Frontend", skills: ["Angular", "React", "HTML", "CSS", "Tailwind CSS", "Responsive Design"] },
          { title: "Backend", skills: ["Node.js", "REST APIs"] },
          { title: "Veritabanı", skills: ["MongoDB", "SQL"] },
          { title: "Araçlar ve Teknolojiler", skills: ["Git", "GitHub", "Flet", "Raspberry Pi", "OpenCV"] },
          {
            title: "Kavramlar",
            skills: [
              "API Entegrasyonu",
              "Kimlik Doğrulama",
              "Runtime Rendering",
              "UI Rendering",
              "State Management",
              "JSON tabanlı UI Sistemleri",
            ],
          },
        ],
      },
      experience: {
        kicker: "Deneyim",
        heading: "Profesyonel Deneyim",
        items: [
          {
            title: "No-Code Platform Runtime Developer",
            company: "IDEA Teknoloji",
            date: "2026 - Günümüz",
            bullets: [
              "No-code platform için Flet kullanarak runtime rendering sistemi geliştirdim.",
              "Frontend tasarım aracının ürettiği JSON şemalarından dinamik UI bileşenleri render ettim.",
              "Event handling, API istekleri ve state management mantığını uyguladım.",
              "Gerçek geliştirme ortamında frontend ve backend ekipleriyle çalıştım.",
              "Tablolar, layoutlar, butonlar, ikonlar ve dinamik aksiyonların render edilmesi üzerinde çalıştım.",
            ],
          },
          {
            title: "Web Geliştirme Stajyeri",
            company: "Beşir Camaleddin Company",
            date: "2025",
            bullets: [
              "Frontend ve backend web uygulaması geliştirmeye destek oldum.",
              "Takım tabanlı geliştirme süreçlerine katıldım.",
              "API ve UI entegrasyon görevleri üzerinde çalıştım.",
            ],
          },
        ],
      },
      projects: {
        kicker: "Projeler",
        heading: "Seçili Çalışmalar",
        github: "GitHub",
        liveDemo: "Canlı Demo",
        items: [
          {
            name: "No-Code Platform Runtime System",
            description:
              "Sürükle-bırak frontend tasarımcısının oluşturduğu JSON şemalarını okuyup dinamik UI sayfaları render eden Flet tabanlı runtime sistem. Bileşenler, layoutlar, tablolar, butonlar, eventler, HTTP aksiyonları, state management ve backend entegrasyonunu destekler.",
            tech: ["Flet", "Python", "REST APIs", "JSON", "Runtime Rendering"],
          },
          {
            name: "Chatify - Web Messaging Application",
            description:
              "Node.js, HTML, CSS, JavaScript ve MongoDB Cloud kullanılarak geliştirilmiş web tabanlı mesajlaşma uygulaması. Kullanıcı ve sohbet verilerini saklar, full-stack web geliştirme kavramlarını gösterir.",
            tech: ["Node.js", "JavaScript", "HTML", "CSS", "MongoDB Cloud"],
          },
          {
            name: "Raspberry Pi Face Recognition Door Lock",
            description:
              "Raspberry Pi ve OpenCV kullanan akıllı kapı kilidi sistemi. Kullanıcı kimlik doğrulaması için yüz tanıma uygular ve donanım ile yazılım bileşenlerini entegre eder.",
            tech: ["Raspberry Pi", "Python", "OpenCV", "Embedded Systems"],
          },
        ],
      },
      education: {
        kicker: "Eğitim",
        heading: "Eğitim, Sertifikalar ve Diller",
        university: "Sivas Cumhuriyet Üniversitesi",
        degree: "Bilgisayar Mühendisliği Lisans",
        educationDate: "2022 - 2026",
        graduating: "2026 yılında mezun olacak",
        certification: "Cisco CCNA / CCNP",
        academy: "Cisco Networking Academy",
        certificationDate: "2021 - 2022",
        languagesTitle: "Diller",
        languages: ["Arapça - Ana dil", "Türkçe - İleri (C1)", "İngilizce - Orta (B1)"],
      },
      contact: {
        kicker: "İletişim",
        heading: "Birlikte Bir Şeyler Geliştirelim",
        email: "E-posta",
        phone: "Telefon",
        location: "Konum",
        locationValue: "Sivas, Türkiye merkezli",
        nameLabel: "Ad",
        namePlaceholder: "Adınız",
        emailLabel: "E-posta",
        emailPlaceholder: "your@email.com",
        messageLabel: "Mesaj",
        messagePlaceholder: "Projenizi veya fırsatı anlatın",
        send: "Mesaj Gönder",
        sending: "Gönderiliyor...",
        success: "Teşekkürler. Mesajınız başarıyla gönderildi.",
        error: "Üzgünüz, mesaj gönderilemedi. Lütfen tekrar deneyin veya doğrudan e-posta gönderin.",
      },
      footer: {
        rights: "© 2026 Ahmed Sherif. Tüm hakları saklıdır.",
        tagline: "Junior Full-Stack Developer · Mısır vatandaşı",
      },
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: localStorage.getItem("portfolioLanguage") || "en",
  fallbackLng: "en",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
